from __future__ import annotations

import argparse
import warnings
from datetime import datetime, timezone
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = BACKEND_ROOT.parent
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "artifacts" / "experiments"
DEFAULT_SEEDS = [11, 29, 47, 71, 97]
DEFAULT_PROTOCOL = "evaluation_protocol_v1"

MODEL_SPECS = {
    "bert": {"model_version": "mv_bert_base_uncased_fast_v1.0.0", "checkpoint": "bert-base-uncased"},
    "finbert": {"model_version": "mv_finbert_fast_v1.0.0", "checkpoint": "ProsusAI/finbert"},
    "fomc_roberta": {
        "model_version": "mv_fomc_roberta_fast_v1.0.0",
        "checkpoint": "gtfintechlab/fomc-roberta-any-exp",
    },
}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate pre-filled pre-run configuration files for first-wave NLP baseline candidates."
    )
    parser.add_argument("--dataset-version", required=True, help="Dataset version id.")
    parser.add_argument("--feature-version", required=True, help="Feature version id.")
    parser.add_argument("--training-package-id", required=True, help="Training package id.")
    parser.add_argument("--owner", default="unknown", help="Run owner.")
    parser.add_argument("--protocol", default=DEFAULT_PROTOCOL, help="Evaluation protocol.")
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT), help="Run docs output root.")
    parser.add_argument(
        "--date-token",
        default=datetime.now(timezone.utc).strftime("%Y%m%d"),
        help="Date token for run_id, e.g. 20260324.",
    )
    return parser.parse_args()


def _format_pre_run(
    *,
    run_id: str,
    protocol: str,
    dataset_version: str,
    feature_version: str,
    training_package_id: str,
    model_version: str,
    checkpoint: str,
    seed: int,
    owner: str,
) -> str:
    started = datetime.now(timezone.utc).isoformat()
    return f"""# Pre-Run Configuration (Filled Example)

## Run Header
- run_id: {run_id}
- evaluation_protocol: {protocol}
- dataset_version: {dataset_version}
- feature_version: {feature_version}
- training_package_id: {training_package_id}
- model_version: {model_version}
- runtime_mode: fast
- seed: {seed}
- owner: {owner}
- started_at_utc: {started}

## Data and Split Configuration
- source datasets:
  - hf_fomc_communication (research_only)
  - kaggle_fed_statements_minutes
  - scraped_fed
- final record count: <fill after package export>
- split strategy: expanding walk-forward
- fold count: <fill from fold manifest>
- horizon set: 1d, 3d, 5d, 10d
- excluded ranges: none

## Model Configuration
- model family: transformer text classifier
- base checkpoint: {checkpoint}
- task: 3-class classification (hawkish/dovish/neutral)
- optimizer: AdamW
- learning_rate: 2e-5
- batch_size: 16
- epochs: 3
- max_length: 512
- adaptation policy: disabled (baseline static run)

## Runtime Constraints
- max runtime budget per run: 90 minutes
- expected latency target: p50 < 120ms, p95 < 250ms
- hardware profile: local workstation

## Leakage and Validation Checks
- no future-aware feature generation: pass
- scaler/tokenizer fit policy (train-only): pass
- duplicate/source leakage scan complete: pass
- pseudo-label holdout isolation verified: pass

## Approval to Execute
- reviewer: self-reviewed
- approved: yes
- comments: First-wave NLP baseline run generated by CLI.
"""


def main() -> int:
    warnings.warn(
        "app.data.generate_baseline_run_specs is deprecated. Use app.data.baseline_spec_generator instead.",
        DeprecationWarning,
        stacklevel=1,
    )
    args = _parse_args()
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    for _, spec in MODEL_SPECS.items():
        model_version = spec["model_version"]
        checkpoint = spec["checkpoint"]
        for seed in DEFAULT_SEEDS:
            run_id = f"run_{args.date_token}_epv1_{model_version}_s{seed}"
            run_dir = output_root / run_id
            run_dir.mkdir(parents=True, exist_ok=True)
            pre_run_path = run_dir / "pre-run-configuration.md"
            pre_run_path.write_text(
                _format_pre_run(
                    run_id=run_id,
                    protocol=args.protocol,
                    dataset_version=args.dataset_version,
                    feature_version=args.feature_version,
                    training_package_id=args.training_package_id,
                    model_version=model_version,
                    checkpoint=checkpoint,
                    seed=seed,
                    owner=args.owner,
                ),
                encoding="utf-8",
            )
            print(f"Wrote {pre_run_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

